export const ANNONCE_LIST_REQUEST = 'ANNONCE_LIST_REQUEST';
export const ANNONCE_LIST_SUCCESS = 'ANNONCE_LIST_SUCCESS';
export const ANNONCE_LIST_FAIL = 'ANNONCE_LIST_FAIL';

export const ANNONCE_DETAILS_REQUEST = 'ANNONCE_DETAILS_REQUEST';
export const ANNONCE_DETAILS_SUCCESS = 'ANNONCE_DETAILS_SUCCESS';
export const ANNONCE_DETAILS_FAIL = 'ANNONCE_DETAILS_FAIL';

export const ANNONCE_CREATE_REQUEST = 'ANNONCE_CREATE_REQUEST';
export const ANNONCE_CREATE_SUCCESS = 'ANNONCE_CREATE_SUCCESS';
export const ANNONCE_CREATE_FAIL = 'ANNONCE_CREATE_FAIL';
export const ANNONCE_CREATE_RESET = 'ANNONCE_CREATE_RESET';

export const ANNONCE_REVIEW_CREATE_REQUEST = 'ANNONCE_REVIEW_CREATE_REQUEST';
export const ANNONCE_REVIEW_CREATE_SUCCESS = 'ANNONCE_REVIEW_CREATE_SUCCESS';
export const ANNONCE_REVIEW_CREATE_FAIL = 'ANNONCE_REVIEW_CREATE_FAIL';
export const ANNONCE_REVIEW_CREATE_RESET = 'ANNONCE_REVIEW_CREATE_RESET';

export const ANNONCE_UPDATE_REQUEST = 'ANNONCE_UPDATE_REQUEST';
export const ANNONCE_UPDATE_SUCCESS = 'ANNONCE_UPDATE_SUCCESS';
export const ANNONCE_UPDATE_FAIL = 'ANNONCE_UPDATE_FAIL';
export const ANNONCE_UPDATE_RESET = 'ANNONCE_UPDATE_RESET';

export const ANNONCE_DELETE_REQUEST = 'ANNONCE_DELETE_REQUEST';
export const ANNONCE_DELETE_SUCCESS = 'ANNONCE_DELETE_SUCCESS';
export const ANNONCE_DELETE_FAIL = 'ANNONCE_DELETE_FAIL';
export const ANNONCE_DELETE_RESET = 'ANNONCE_DELETE_RESET';

export const ANNONCE_CATEGORY_LIST_REQUEST = 'ANNONCE_CATEGORY_LIST_REQUEST';
export const ANNONCE_CATEGORY_LIST_SUCCESS = 'ANNONCE_CATEGORY_LIST_SUCCESS';
export const ANNONCE_CATEGORY_LIST_FAIL = 'ANNONCE_CATEGORY_LIST_FAIL';
