export const MATPROD_LIST_REQUEST = 'MATPROD_LIST_REQUEST';
export const MATPROD_LIST_SUCCESS = 'MATPROD_LIST_SUCCESS';
export const MATPROD_LIST_FAIL = 'MATPROD_LIST_FAIL';

export const MATPROD_DETAILS_REQUEST = 'MATPROD_DETAILS_REQUEST';
export const MATPROD_DETAILS_SUCCESS = 'MATPROD_DETAILS_SUCCESS';
export const MATPROD_DETAILS_FAIL = 'MATPROD_DETAILS_FAIL';

export const MATPROD_CREATE_REQUEST = 'MATPROD_CREATE_REQUEST';
export const MATPROD_CREATE_SUCCESS = 'MATPROD_CREATE_SUCCESS';
export const MATPROD_CREATE_FAIL = 'MATPROD_CREATE_FAIL';
export const MATPROD_CREATE_RESET = 'MATPROD_CREATE_RESET';

export const MATPROD_REVIEW_CREATE_REQUEST = 'MATPROD_REVIEW_CREATE_REQUEST';
export const MATPROD_REVIEW_CREATE_SUCCESS = 'MATPROD_REVIEW_CREATE_SUCCESS';
export const MATPROD_REVIEW_CREATE_FAIL = 'MATPROD_REVIEW_CREATE_FAIL';
export const MATPROD_REVIEW_CREATE_RESET = 'MATPROD_REVIEW_CREATE_RESET';

export const MATPROD_UPDATE_REQUEST = 'MATPROD_UPDATE_REQUEST';
export const MATPROD_UPDATE_SUCCESS = 'MATPROD_UPDATE_SUCCESS';
export const MATPROD_UPDATE_FAIL = 'MATPROD_UPDATE_FAIL';
export const MATPROD_UPDATE_RESET = 'MATPROD_UPDATE_RESET';

export const MATPROD_DELETE_REQUEST = 'MATPROD_DELETE_REQUEST';
export const MATPROD_DELETE_SUCCESS = 'MATPROD_DELETE_SUCCESS';
export const MATPROD_DELETE_FAIL = 'MATPROD_DELETE_FAIL';
export const MATPROD_DELETE_RESET = 'MATPROD_DELETE_RESET';

export const MATPROD_CATEGORY_LIST_REQUEST = 'MATPROD_CATEGORY_LIST_REQUEST';
export const MATPROD_CATEGORY_LIST_SUCCESS = 'MATPROD_CATEGORY_LIST_SUCCESS';
export const MATPROD_CATEGORY_LIST_FAIL = 'MATPROD_CATEGORY_LIST_FAIL';
